import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LoginProvider } from './context'
import { SocketProvider } from './socketContext'
import Background from "./components/background";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ConnectSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white overflow-hidden`}
      >
        <Background />
        <SocketProvider>
          <LoginProvider>
            {children}
          </LoginProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
